.TH Lasts "1" "November 9, 2011" "Multicat 2.0"
.SH NAME
lasts \- Indicate duration of file based on multicat's auxiliary file
.SH SYNOPSIS
.B lasts
<aux file>
.SH DESCRIPTION
LasTS is a companion application for multicat, to manipulate auxiliary files.
It returns the total duration of a file, based on the auxiliary file created
by multicat or ingesTS.
.SH SEE ALSO
.BR aggregartp (1),
.BR reordertp (1),
.BR ingests (1),
.BR multicat (1),
.BR offsets (1).
.br
Read the README file for more information about the configuration of lasts.
.SH AUTHOR
lasts was written by Christophe Massiot.
.SH LICENCE
This program is free software; you can redistribute it and/or modify it under the terms of
version 2 of the GNU General Public License as published by the Free Software Foundation.
.PP
This manual page was written by Rémi Duraffort <ivoire at videolan dot org>,
for the Debian project (and may be used by others).
