.TH Offsets "1" "August 23, 2010" "Multicat 1.0"
.SH NAME
offsets \- Manipulate auxiliary files created by ingests
.SH SYNOPSIS
.B affsets
<aux file> <27 MHz timestamp>
.SH DESCRIPTION
Offsets is a companion application for multicat, to manipulate auxiliary files.
Given an offset in time from the beginning of the file, it returns the offset
of the position in number of packets.
.SH SEE ALSO
.BR aggregartp (1).
.BR desaggregartp (1).
.BR ingests (1).
.BR multicat (1),
.br
Read the README file for more information about the configuration of offsets.
.SH AUTHOR
offsets was written by Christophe Massiot.
.SH LICENCE
This program is free software; you can redistribute it and/or modify it under the terms of
version 2 of the GNU General Public License as published by the Free Software Foundation.
.PP
This manual page was written by Rémi Duraffort <ivoire at videolan dot org>,
for the Debian project (and may be used by others).
